//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int forecastId { get; set; }
        public int geoId { get; set; }
        public System.DateTime lastupdate { get; set; }
        public System.DateTime nextupdate { get; set; }
        public System.DateTime timeFrom { get; set; }
        public System.DateTime timeTo { get; set; }
        public int period { get; set; }
        public int temp { get; set; }
        public string symbol { get; set; }
    
        public virtual Geoname Geoname { get; set; }
    }
}
