//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geoname
    {
        public Geoname()
        {
            this.Forecasts = new HashSet<Forecast>();
        }
    
        public int geoId { get; set; }
        public string geonameId { get; set; }
        public string name { get; set; }
        public string adminName1 { get; set; }
        public string countryName { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<System.DateTime> nextUpdate { get; set; }
        public string adminName2 { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual ICollection<Forecast> Forecasts { get; set; }
    }
}
